### ISSUE TITLE
I got this this error when I run the program ('scbasset_preprocess.py --ad_file h7.h5ad --input_fasta genome.fa --out_path preprocess')

### ISSUE THREAD

**Issue by kongfuwz** [calico/scBasset#12]
process 9000 peaks takes 8.4 s
process 10000 peaks takes 9.1 s
Traceback (most recent call last):
  File "/home/zhu/.0/0/atac/../pgm/scBasset/bin/scbasset_preprocess.py", line 60, in <module>
    main()
  File "/home/zhu/.0/0/atac/../pgm/scBasset/bin/scbasset_preprocess.py", line 56, in main
    make_h5_sparse(ad_test, '%s/test_seqs.h5'%output_path, input_fasta)
  File "/home/zhu/.0/0/pgm/scBasset/scbasset/utils.py", line 142, in make_h5_sparse
    batches = np.array_split(np.arange(n_peaks), n_batch) # split all peaks to process in batches
  File "<__array_function__ internals>", line 180, in array_split
  File "/home/zhu/.0/base/envs/rna/lib/python3.10/site-packages/numpy/lib/shape_base.py", line 778, in array_split
    raise ValueError('number sections must be larger than 0.') from None
ValueError: number sections must be larger than 0.

How to solve it?

**Comment by hy395** [comment]
Hi,

I don't have access to your data. But it looks like it complains because within the scbasset_preprocess.py code, the ad_test data has 0 entries. Something might be wrong in the split_train_test_val() step. Could you check the "test_ids" in split.h5 file, and see if it is an empty array?

**Comment by kongfuwz** [comment]
> 

Hi,

I have checked the key "test_ids" in split.h5 file, it isn't an empty array and it's shape is (664,).

**Comment by kongfuwz** [comment]
I have fixed this error，thank you!
